apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples:  |-
      [
        {"apiVersion":"argoproj.io/v1alpha1","kind":"ArgoCD","metadata":{"name":"argoproj"},"spec":{}}
      ]
    capabilities: Basic Install
    categories: "Integration & Delivery"
    description: Manages the installation of Argo CD.
    certified: "false"
    containerImage: quay.io/disposab1e/argocd-operator:latest
    createdAt: 2019-10-18T08:00:00Z
    support: Community
    repository: https://github.com/jmckind/argocd-operator
  name: argocd-operator.v0.0.1
  namespace: placeholder
spec:
  maturity: alpha
  provider:
    name: John McKenzie
  version: 0.0.1
  customresourcedefinitions:
    owned:
      - kind: ArgoCD
        name: argocds.argoproj.io
        version: v1alpha1
        displayName: ArgoCD
        description: 'Represents the Argo CD installation.'
      - kind: Application
        name: applications.argoproj.io
        version: v1alpha1
        displayName: Application
        description: 'Represents a definition of Application resource.'
      - kind: AppProject
        name: appprojects.argoproj.io
        version: v1alpha1
        displayName: AppProject
        description: 'Represents a logical grouping of applications.'
  description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.
  displayName: Argo CD Operator
  links:
  - name: Argo CD
    url: https://argoproj.github.io/argo-cd/
  - name: Argo CD Operator
    url: https://github.com/jmckind/argocd-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACIAAAAyCAYAAAA5kQlZAAAACXBIWXMAAAsTAAALEwEAmpwYAAAF8mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMTktMTAtMThUMTU6Mjk6NDQrMDI6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDE5LTEwLTE4VDE2OjU2OjAzKzAyOjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDE5LTEwLTE4VDE2OjU2OjAzKzAyOjAwIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjkyYTA4YjFhLTA5ZmYtNDM4Yy1iMzgzLWRkM2Y2ZjhiNzYzZCIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo5ODZjNmMzZC04ZjhjLTQxMWYtYmM3NC00NGQ4ZGQwYjNlM2IiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo5ODZjNmMzZC04ZjhjLTQxMWYtYmM3NC00NGQ4ZGQwYjNlM2IiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjk4NmM2YzNkLThmOGMtNDExZi1iYzc0LTQ0ZDhkZDBiM2UzYiIgc3RFdnQ6d2hlbj0iMjAxOS0xMC0xOFQxNToyOTo0NCswMjowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKE1hY2ludG9zaCkiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjkyYTA4YjFhLTA5ZmYtNDM4Yy1iMzgzLWRkM2Y2ZjhiNzYzZCIgc3RFdnQ6d2hlbj0iMjAxOS0xMC0xOFQxNjo1NjowMyswMjowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKE1hY2ludG9zaCkiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+q19M6gAAE0NJREFUWIWNeHmQXWd15+9833eXd9/Wr/dudbdae8tGq63FRrLkDXtMgQ0mxkMcKgEMhoJMGIcEkikmIQkkZAoGkwAODBkGDEMGguPEBoMtIcuLLNmSrV2ytbV679f99neXb8sfryXZhMzMqfqq7r117zm/s5976JHvvIRLxDlDtRpj7OIEiuVJRIlF2vPQaCZQSiGTcmGBzsjY5Ro0pAXPGSIfACNrYqFtQ0CPkzSvwdJUKnCV67qoyRBMA1EzBlkHhe4cwC1kqECMAAAC/w8iAMwYRrDrK0Jsjz13KHSEZ4WwFtCMSFos8LJGMG3IkUqKZjQtjDngxvIFzlnTkvm/yvn1QGwLAYeFkXp53XPvku255XPKNOqRnO9LC0HWamsAay2xha8sYME5ix3hRYHf1YzV3UGtvqMg9eMCeBG0wPvXEPs3GKwF4wTHWtSb8rbxIHiw3N0+OBklZ1Z05+RvbF0+lIRSKakJ1jKyltA6jKzlZAxxpROhdBmuGK92F1KT6ez91Uj/NtfGI6L/PyCMMZhQIgT/nZmujvfW0v4Mk3I6L7jbmQ/Sw/2FDmWsscZYAcMZLGOwJGA4h3kjP2JaczdRZZVJXZzubr8uSvm/DymDlsN/xTWM88veEIKjI8uwZ6Z4z1RnsJ2l/LMiTsyKgY72fNp3DpyenH721XPj7fm0O4tMZcx6TQ7DCSBFXPtI3E5bz/tQrgLTCzK4SBLLUu5oyW0fSDemPtrH6W9CIH4TkNLUOADAEQyTDYnXx4s3VnrStxvhnUtrjTUr+rrDRKmXX58sOpAC2fbmKZuf3YTRVRvpwrIBlHuYVHzKZotHncHzz9OKo56NxSDKvRJcWcCCCDyR3DrOeGOwe9Vc2Hh/Wjjf5MSvAImb9daVwxGWG70n6o13slzXZGCMvnq4u6vaiOXJsblSwIw7KbpmfdLef1M/eOAOe+xacgkgCwgLNBUgHRx0Fp/7c+cd3z1FPaMr7MyABhkLspYIQimSvjsx1ow2DtUbW22a71PSthJj81vvQagJkbQ4V2q8t9nZtgjKzK4e6uhU2tij52dLGUHetOiYy1OU+Xv78Kc2sVMrEt6Bug4QsywSnkaTZ6AUx7AeLbxHv7ztVbH0/Cs0cKYHtTYNdil3iWmjdRAIG8WDLksOIM0kCYCV6lVUoyaK5dqyOdddKy2K/flUNuW44vTYXMUTjDdE0DRg9HXzPz+xOLnQFW96H9gtd4EJBsQhYAy4MFBcYBaLwK3lXwn/x0eG7VzvOLUV3xTEFozIVCqu3+vzzOa+QgHd+QKY1oSwFKLUDNclvstTjKne9kwwPletJ9LolENi0ubnfwMvvnUZjfaXaRC2Ng9bLrYqB2OXKgiYAAQkZqkbKRv5H5RPvy0iTxrQlepBANfGmMALq4leF86EmJ+qgQmWhe8QV76zPAbC9rTnEBFmKvXIcxhvWifuRq3tTjp6PVgO1vUQHX4J4d5dgDEgx7mk6YIgAodCQh24XZ/aMmLGBoqUqXDYK1YxlhinRlM4XVFoOmp1BaZV87ZYJz+Wvi8IVM4Frl9pxlJrwGHgVes1e1klP+TWejVcCCbBMwHI9wHGW9Z4g7YkOBgziImQErGzGPPdIdyYYN9YPIgRRbHjqHKj+b+FoNuEEMm2+aK8M8ny/Q6n2HeFM1NuNC1gXWhn1ivM98v5Du/kcVFJ0ogtB08xeMsGAcZgk1a5IMFAHIguXISpheCMkGVF2BWazaXbSkuj2X7Q5dpCMFZZzgxz+C0w6pDgJCw5HJpADmOcACTKaA9GjLuds0P10b7PnfnGB+3O+5C97X3IKInqv/wQzX0/RWp1L8jzYbUBYBEeOw9augltd90Hnm2D2vMofu+pH9xzdjg3eb6wdGoomumSxDUAkLWwBGaIwA20aBWchSBiIGsBawzFzEmkNPoLr339/at/554+++4HL/eD9rUbUfn2IMKffA3B+iUghyE8cg7imrej/Y//6ooD1l2DvpWLM3/5t1+5/wOp//rXVZZqpm3sm0slngDb6j0LAWQBMoBZ6LoMoBnRVtp8ce9V27csvQrvfhDlcgVr16zFnXfeCQDIf+DjEGt2QE1Ow5bLoK6VaP9PnwUA/P6nPoWuri4cP3UauP1DWHbDlu63n//Z1qKTr7yp+dpLwkGMCETGgsFCGaMZAUxwKGJqRTwxhFUbAQBzxVkcOXoEhw8fRpwkrWK88mqYZgxdrcNZfjWQSQMAThw/jmKxiNFzZxcsswMjarrfwuJScWtZwoJZC60MCamthTHgxpjIwCplbMrl3MaW6vCaqJcAAMuXL8e+ffsQBAE8120pVK8BnADOYaLmZUUfeughfPozn8H2bdtaDxolNCEkiC6njiUCM9CkLBRgmbH040zK+6QvbaKMyVcjGRXSnpdRYfBi+9qj9Rf2RiiPAQC2bNmCNWvWAADk6AXE+3dDdLRBdBQgDz+P6JWXAQDLli27AiJpALsfwy/zaw97RjochqMVlykWJg60/pPFi7u/xxjnh4O8/98z3BbJ2LZSI45dx2FDTtRxumNk/BuVJU/gCw/AVMqXNVYzMyj91afB1Qx4WwHwUnCyCpUvfxby7Jkr78US+OJH8H8uus+9OLD9WI8st1vQQkSyDG82pMPs57ngx4SKFeApiES9nGZ8UyVRqDbjZKCrLV26ONv98OoPPJac/l/q0w/svKe2/jYobZAcegYilcAbGYaJFGAt3MUDwIVxzP/n98DZuAMsnUHbqz/HI42BPX+29g++M6TmujkM15Zp6zJmmmG6TfPdHbmMTEoS/KplOxHXJUxDzlhgJMykeprNpDTUnc/6UO5sJW5O9Y3MvEe8tMMffVlExVG4vVmIvm7YxALGtNJQG/CONogMgxk/AXfyKETe4HOLP/KdkkrVB/V8jyShiGATYmm/XI0X9eZ/5OSDpnEJYvmG3lYGOByN+ebPD5bCjzdzKX5+qlR1BRNpUl5bGObjoGAyWR8OfBBxsPlZKK1Ahd4WkFoZrBwCHX0Qg2m4kNBG2kJSy2WRCSQJBQtoT1hdbBQGBfvnvuH8bKIMABfMC3x4gQ8n5SGTzxztCpu7VK05VIxUODVfb6Y4nJCcpGHdCEoBUkOW52B23IPsyg1Qrx2CPP0KnEwW/JbfhApDII5BSkMZrkM4MYMlWAs4XDfqSW+/aZ7ZunbxE73MRz/z0M88iIsTl0LLwEKg0NH7j6xRGbho1Co/5V3kiSFJXDbhhIApEHfQZkL84+EzuPYPHsLwLe8GqiVUtr4XT377YdxamoTTuxjcRKjDVxJCCau5EVxFsJ2d1WZj6WDPI4obY6WGXWjbTGvg0pHSIGjPqeuvGviaf2H6vFR2MTzGpOVxHU4TMFBagy1eiui5R3Hzjpux27kKx1a+Aze/90M48NAfo7ByBRJLIBiEcGQEnpBg0Ix6spNl26nUV5nvjGtt8MZfC0YEvPEoqRAZG/U59OWe2eIBasbDkecFTXJCwAAgNMoh7nvbZmyPTuCmVYN4S2ca4ZPfwR+9YwtsDBhtABiE5DSajse4TpYUZuenC2HyJcX4mDYG9Cu/FGKO5S7faGthRBpZQZjk2ajbMX83UKq+fqLWvmW0LQO4BkwDUmkkDYVv3bcT6/eeRjFM8Omdq5DhAqVyEyQEwBXGbEZOVVx/XX1qryHx2ASlItcKpEUW7a4HDg/GtsZZevrjv3elB1nAdThSDhDPz+K024+nkxGsD2q4033uR0vsxN0NLwfGDLQ08ARHqjMLcIKab6ARJmAOgzGEQDUxGwYHfyy379gr++o3i5NYZ4to8gBB1kPaZSDwyzFC5kM3vMlExlhoA7guQ82kMCfy6Ot2+qkxs6+SsEEGAvMIXAAgwBjTmlcZa91LwCQWhggpxMa36R3jcfrZPFWRFxogF0gUtLGXQQAA6Q/efDloCBYNchCRAMGCE+3gOv5Is2Fv551ewSsAqmGNkZZazRtY2Cq0RohWCFkmYJ0MsbgGYF5XAp/2hcz5PiPvhwIU25awK2QB8bP86pZWAEImsCaaxRJZQkwCfhLOSuJ7kU7/vZPl26xufJZ7bJq5lLUaGViLBRdDMABEIE4RMZSs0v2u7/1NKJwfybi+IY3GOeblbcxdMGvfjMRaiCeyq5BICSJCbAnHgkVYFAg4SYT15bPH80n1+IBfQsjcPisZiPMJQA853MCAORrwFgY8xWAiDZbA0Jg11E+umUkX7J6xsHOPBaGU68HB/FLIWhVxIsGIYK2F57oQBR1C6hYQGIMolcaElwf3DC60L0HcbOB+tQdL4rG4hDQcoycB210nl7tWMw4DC4IFdExe3bHSMMKoJL7ZU1HkeQo/77wJY34PsogBY1AWFrGKW5sHYxE4XmsMlUpBSolYSnCVIGNl1k3Cj+bC0l2SHLHLXYcy7yimkMAndVzAVmdZvl0TDxgsOAwAuNMs28tgTcomRxwrkTKy+C/OJpRsGp1JZacTNX430MmilJYQMoIjI7gqQmAUGKxFV2cH8vksGBFpY35YrTXKUuqvNaLkJ91y7tzzZvAvfuhu3eibuj7iDd/RJLGImIAGwSUDlywsQJJ7CEHtr/rL3pk2dTyTXr/qifQ1n3Rk42QSxbtVor5SqYWj2mJ3OgjyQRAgn8sCBAjHcRD4Hjbv2IpNmzfY3U88ObH/5SNMGgecMzSsOyB08kdjOo3Y93E+4UsyhotSrXyiz9dLy4ZXNaBywvbMVirHsz4tOSPF6nW+Y16yA3/YSAwicuDAQBsNT4CtWdY/PTKyrBbHEgePn8P45CwY5xwXxyYwPT0Lzhm2v/WaT9563VvacmnvWCOSSHOLW71pPJg5hpnIXHjs5MRXBUvKNUXCY9IcijLe8828FzBpSgmQcrTZfXrsW6+WcfwTuZO4NzWGPNNoJhK+I2a2rV0ydMcdN967dPVqMz1XxvnRcQjOwW+88Xa0t+dx6vRZOrD/FVGqNc1rY8W75yqNB9IOx4iZng/GXnp8196ndv1ivsO9fSh/07pc2Pet2aGOWzNFZ7/p82ZMLrUlNcm+PT/cfX2u6g34zrIfnbNTJw7t+ec2Wzu5qJDrqLFMri5tupqos5Mz8/uf2r1fvHZ2zGYy6YXNpbUPRlFyIJvNPBvHyaFnnn15bHxi5nsOZ/CDDP7h5MTf3vvILz//T9VF+TVXb9jZlfL6/8v5JXbAj627yMdMLL97phl+CT1ZbG5r4E8vDMPwVOe1V63auhcjy97/g+cefviV859zc21N1+EozlYeen7f4fF6rfZqOvBf0Eq/qLX5osjlMjvPnL14bVshD600/FQKRAwpPwWjZe2nTzz6aKVcnS+s2HztGVPAeKWMOztqtD07h8888uqX//KFqc8BiCoHOorfvGvDn650upyn5n1UPB/ZZZu3Vvbu4U8/+fj3t23Z+bGUn1qfJAn5QdCfKNMvVYRESuQz6by4ZtXgN/rT7BU3lVKJ1G2Mwb84U72pWK6sHOjrza7feP2Hd+964mNh6exXg+Hur1Upg8erDr5V7DHPJ3z58pWTDwkG5xne7dx3ZkQuzjJHWIm06yAZP/F1AHvXbtj6YS+VXj8xNY22jD8x3FP4hVS67rq8RNYiHfjHaPzcGVSKRTiOw1OuEL7D47MXxgt79h9/qZHYpUODg/jpzx579NlfPv7XGzduGki3D9yaKLbFcYPh3kJ7lgve2kxYjen5UrMZN0ddrg+aaG7X/n3PHlq38Yb77r77P35ybHwcgkzp2quXbF4y1Pd6JhN4tUakmRDKDQLQxOgoquUSlFT4xdMvQBlCd3fhnrni/DfL9TCX8n10dvXh9bPn7JnXDh8opOgFT1BJKU2JNB6InFars9IRLBaCawNKlyO7sX9w1Y2rVqzg83PTCKMIGd9V2Vzud+drja+3BQ5uuH4D0tksuOuBJi+OolGt4tDRM3hh/1FuYQ9oozekUykwRtDaQHCo5cNDRQunMD4z6yVJDOi4JsiMaa1jAJZz7hiwAU1um+v56O0oyLasXzx++mwhjKXPFtp0FCdwHTERx3L95g0js9dtWgPH90FhvQ5Zr0N4PlL5HMpjY/ceOXLqPQdPnf8PHfns2MiywV8M9nXti+PGniiK2wttHWubUdT7xDOHPjE5MzeYzQQAgEYYIh2kqjdtuuqhob6e1yrV8tHpmemJJUuWXlcs1bedOjd+w8WpmbVrli/+5cY1K38yU2/83fnxSZMNfPR0d4E++sADmJ2aRJDyYYnQqNWwfHi4/ZadN95QLpWm9zy392C1Gcanzp6HUhJrRlYBKsGGa7Z9caZOn5JJCBDBgmP1UMcjXM7f99TzB3D67FkcePkg3vX2O9CRz/Ft11/3lkX9g8v3vfjCvucOHBi//2Mfw8iqEczPzwP/ZoK9Qiyfy1KcJBRFMQHgADwACkAIwHzlC59f91v3/vYfHjl5IgKsXrViZWHXrie/9L4P3//8wrCRAuCitepWQnCbDgJTqdYAwHR3dyMIAmitAWv/XSAA4CwwYq0ZqsVwQYjYuG6tvvdd78yUy1Wy1qKjvd3+wz89Vt9/8BADoBe+EQs8+MIzCSD5dcL+FSMN16T53W6zAAAAAElFTkSuQmCC
    mediatype: image/png
  maintainers:
  - name: John McKenzie
    email: argocd-operator@noreply.github.com
  miniKubeVersion: 1.15.0
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: argocd-application-controller
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - delete
          - get
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - list
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/log
          verbs:
          - get
        serviceAccountName: argocd-server
      deployments:
      - name: argocd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: argocd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: argocd-operator
            spec:
              containers:
              - command:
                - argocd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: argocd-operator
                image: quay.io/disposab1e/argocd-operator:latest
                imagePullPolicy: Always
                name: argocd-operator
                resources: {}
              serviceAccountName: argocd-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - argocd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - argoproj.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheuses
          - servicemonitors
          verbs:
          - '*'
        serviceAccountName: argocd-operator
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - appprojects
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
        serviceAccountName: argocd-application-controller
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - get
          - list
          - watch
        serviceAccountName: argocd-dex-server
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - appprojects
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
        serviceAccountName: argocd-server
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
