apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator
  labels:
    app.kubernetes.io/name: {{ include "argocd-operator.name" . }}
    helm.sh/chart: {{ include "argocd-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argocd-operator.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argocd-operator.name" . }}
        helm.sh/chart: {{ include "argocd-operator.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: argocd-operator
      containers:
        - name: argocd-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - argocd-operator
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "argocd-operator"
{{- if .Values.debug }}
            - name: LOG_LEVEL
              value: Debug
{{- end }}