apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: argocds.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: ArgoCD
    listKind: ArgoCDList
    plural: argocds
    singular: argocd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            dex:
              description: Dex defines the Dex server options for ArgoCD.
              properties:
                image:
                  type: string
                version:
                  type: string
              required:
              - image
              - version
              type: object
            grafana:
              description: Grafana defines the Grafana server options for ArgoCD.
              properties:
                image:
                  type: string
                version:
                  type: string
              required:
              - image
              - version
              type: object
            image:
              description: Image is the ArgoCD container image.
              type: string
            redis:
              description: Redis defines the Redis server options for ArgoCD.
              properties:
                image:
                  type: string
                version:
                  type: string
              required:
              - image
              - version
              type: object
            tls:
              description: TLS defines the TLS options for ArgoCD.
              properties:
                ca:
                  description: CA defines the CA options.
                  properties:
                    configMapName:
                      description: ConfigMapName is the name of the ConfigMap containing
                        the CA Certificate.
                      type: string
                    secretName:
                      description: SecretName is the name of the Secret containing
                        the CA Certificate and Key.
                      type: string
                  required:
                  - configMapName
                  - secretName
                  type: object
                enabled:
                  description: Enabled toggles TLS globally.
                  type: boolean
              required:
              - enabled
              type: object
            version:
              description: Version is the tag to use with the ArgoCD container image.
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
