apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: argocd-operator
  template:
    metadata:
      labels:
        name: argocd-operator
    spec:
      serviceAccountName: argocd-operator
      containers:
        - name: argocd-operator
          # Replace this with the built image name
          image: quay.io/john_mckenzie/argocd-operator:latest
          command:
          - argocd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "argocd-operator"
          resources: {}
