apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    purpose: example
    example: lb
spec:
  server:
    insecure: false
    service:
      type: LoadBalancer
